/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.mycompany.exercicioswing;

import java.awt.Color;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author User
 */
public class Exercicio extends javax.swing.JDialog {

    /**
     * Creates new form Exercicio
     */
    public Exercicio(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonGroupSist = new javax.swing.ButtonGroup();
        buttonGroupHD = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        menuPopUp = new javax.swing.JPopupMenu();
        menuCadastrar = new javax.swing.JMenuItem();
        menuExcluir = new javax.swing.JMenuItem();
        menuAlterar = new javax.swing.JMenuItem();
        LabelNome = new javax.swing.JLabel();
        TextDigitarNome = new javax.swing.JTextField();
        LabelCidade = new javax.swing.JLabel();
        ComboCidade = new javax.swing.JComboBox<>();
        PanelSist = new javax.swing.JPanel();
        ButtonWindows = new javax.swing.JRadioButton();
        ButtonLinux = new javax.swing.JRadioButton();
        ComboVersao = new javax.swing.JComboBox<>();
        LabelVersao = new javax.swing.JLabel();
        PanelHD = new javax.swing.JPanel();
        Check320 = new javax.swing.JCheckBox();
        Check500 = new javax.swing.JCheckBox();
        Check1TB = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        buttonIntel = new javax.swing.JRadioButton();
        buttonAmd = new javax.swing.JRadioButton();
        labelRAM = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaRAM = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaRelatorio = new javax.swing.JTable();
        jButtonCadastrar = new javax.swing.JButton();

        menuCadastrar.setText("Cadastrar");
        menuCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });
        menuPopUp.add(menuCadastrar);

        menuExcluir.setText("Excluir");
        menuExcluir.setComponentPopupMenu(menuPopUp);
        menuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExcluirActionPerformed(evt);
            }
        });
        menuPopUp.add(menuExcluir);

        menuAlterar.setText("Alterar");
        menuAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlterarActionPerformed(evt);
            }
        });
        menuPopUp.add(menuAlterar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelNome.setText("Nome");

        LabelCidade.setText("Cidade");

        ComboCidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aracruz", "Colatina", "Serra", "Vitória" }));
        ComboCidade.setSelectedIndex(1);

        PanelSist.setBorder(javax.swing.BorderFactory.createTitledBorder("Sist. Operacional"));
        PanelSist.setToolTipText("Sist. Operacional");

        ButtonGroupSist.add(ButtonWindows);
        ButtonWindows.setMnemonic('W');
        ButtonWindows.setText("Windows");
        ButtonWindows.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonWindowsActionPerformed(evt);
            }
        });

        ButtonGroupSist.add(ButtonLinux);
        ButtonLinux.setMnemonic('L');
        ButtonLinux.setText("Linux");
        ButtonLinux.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonLinuxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelSistLayout = new javax.swing.GroupLayout(PanelSist);
        PanelSist.setLayout(PanelSistLayout);
        PanelSistLayout.setHorizontalGroup(
            PanelSistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSistLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelSistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ButtonLinux)
                    .addComponent(ButtonWindows))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        PanelSistLayout.setVerticalGroup(
            PanelSistLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSistLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ButtonWindows)
                .addGap(18, 18, 18)
                .addComponent(ButtonLinux)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        ComboVersao.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ComboVersao.setEnabled(false);

        LabelVersao.setText("Versão");

        PanelHD.setBorder(javax.swing.BorderFactory.createTitledBorder("HD"));

        buttonGroupHD.add(Check320);
        Check320.setMnemonic('3');
        Check320.setText("320 GB");

        buttonGroupHD.add(Check500);
        Check500.setMnemonic('5');
        Check500.setSelected(true);
        Check500.setText("500 GB");

        buttonGroupHD.add(Check1TB);
        Check1TB.setMnemonic('1');
        Check1TB.setText("1 TB");

        javax.swing.GroupLayout PanelHDLayout = new javax.swing.GroupLayout(PanelHD);
        PanelHD.setLayout(PanelHDLayout);
        PanelHDLayout.setHorizontalGroup(
            PanelHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Check320)
                    .addComponent(Check500)
                    .addComponent(Check1TB))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        PanelHDLayout.setVerticalGroup(
            PanelHDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelHDLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Check320)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Check500)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Check1TB)
                .addGap(24, 24, 24))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Processador"));

        buttonGroup1.add(buttonIntel);
        buttonIntel.setMnemonic('I');
        buttonIntel.setText("Intel");

        buttonGroup1.add(buttonAmd);
        buttonAmd.setMnemonic('A');
        buttonAmd.setText("AMD");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonIntel)
                    .addComponent(buttonAmd))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonIntel)
                .addGap(18, 18, 18)
                .addComponent(buttonAmd)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        labelRAM.setText("Memória RAM");

        listaRAM.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Menos que 1 GB", "1 GB", "2 GB", "3 GB", "4 GB", "Mais que 4 GB" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listaRAM.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(listaRAM);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Relatório"));

        tabelaRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Cidade", "SO", "Versão", "Processador", "HD", "Memória"
            }
        ));
        tabelaRelatorio.setComponentPopupMenu(menuPopUp);
        jScrollPane2.setViewportView(tabelaRelatorio);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jButtonCadastrar.setText("Cadastrar");
        jButtonCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNome)
                    .addComponent(TextDigitarNome, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PanelSist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ComboCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LabelCidade))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboVersao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(PanelHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelRAM)
                                    .addComponent(jButtonCadastrar)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(LabelVersao, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNome)
                    .addComponent(LabelCidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextDigitarNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelSist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonCadastrar)
                                    .addComponent(PanelHD, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabelVersao)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ComboVersao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(labelRAM)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonWindowsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonWindowsActionPerformed
        ComboVersao.setEnabled(true);
        ComboVersao.removeAllItems();
        ComboVersao.addItem("XP");
        ComboVersao.addItem("Win7");
        ComboVersao.addItem("Win8");
        ComboVersao.addItem("2003 Server");
        ComboVersao.addItem("2008 Server");
        ComboVersao.setSelectedItem("Win8");
    }//GEN-LAST:event_ButtonWindowsActionPerformed

    private void ButtonLinuxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonLinuxActionPerformed
        ComboVersao.setEnabled(true);
        ComboVersao.removeAllItems();
        ComboVersao.addItem("Ubuntu");
        ComboVersao.addItem("Fedora");
        ComboVersao.addItem("Red Hat");
        ComboVersao.addItem("Suse");
        ComboVersao.addItem("Debian");
        ComboVersao.setSelectedItem("Ubuntu");
    }//GEN-LAST:event_ButtonLinuxActionPerformed

    private void jButtonCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarActionPerformed
        String nome = TextDigitarNome.getText();
        String cidade = ComboCidade.getSelectedItem().toString();
        String versao = ComboVersao.getSelectedItem().toString();
        String SO = "";
        String processador = "";
        String hd = "";
        List listRAM = listaRAM.getSelectedValuesList();

        if (buttonGroup1.getSelection().getMnemonic() == 'I') {
            processador = "Intel";
        } else {
            processador = "AMD";
        }

        if (ButtonGroupSist.getSelection().getMnemonic() == 'W') {
            SO = "Windows";
        } else {
            SO = "Linux";
        }

        if (buttonGroupHD.getSelection().getMnemonic() == '1') {
            hd = "1 TB";
        } else if (buttonGroupHD.getSelection().getMnemonic() == '5') {
            hd = "500 GB";
        } else {
            hd = "320 GB";
        }
        
        if (validarCampo()) {
            inserirRelatorio(nome, cidade, versao, SO, processador, hd, listRAM);
            ComboCidade.setSelectedItem("Colatina");
            ComboVersao.setEnabled(false);
            ComboVersao.removeAllItems();
            Check500.setSelected(true);
            TextDigitarNome.setText("");
            ButtonGroupSist.clearSelection();
            buttonGroup1.clearSelection();
            listaRAM.clearSelection();
            
        }
       
    }//GEN-LAST:event_jButtonCadastrarActionPerformed
    
    private boolean validarCampo(){
        LabelNome.setForeground(Color.black);
        String msgErro =  "";
        if(TextDigitarNome.getText().isEmpty()){
            msgErro = msgErro + "Digite um nome válido.\n";
            LabelNome.setForeground(Color.red);
        }
        
        if(msgErro.isEmpty()){
            return true;
        }else{
            JOptionPane.showMessageDialog(this, msgErro, "Cadastro de nome", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
    }
    
    private void menuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExcluirActionPerformed
        int linha = tabelaRelatorio.getSelectedRow();
        if(linha >= 0){
            if (JOptionPane.showConfirmDialog(this, "Deseja excluir essa linha?") == JOptionPane.YES_OPTION) {
                ((DefaultTableModel) tabelaRelatorio.getModel()).removeRow(linha);
            }
        }
    }//GEN-LAST:event_menuExcluirActionPerformed

    private void menuAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlterarActionPerformed
        int linha = tabelaRelatorio.getSelectedRow();
        int coluna = 0;
        if(linha >= 0){
            if(JOptionPane.showConfirmDialog(this, "Deseja alterar essa linha?") == JOptionPane.YES_OPTION){
                TextDigitarNome.setText(tabelaRelatorio.getValueAt(linha, coluna++).toString());
                ComboCidade.setSelectedItem(tabelaRelatorio.getValueAt(linha, coluna++).toString());
                if(tabelaRelatorio.getValueAt(linha, coluna++).toString().equals("Windows")){
                    ButtonWindows.setSelected(true);
                    ButtonWindowsActionPerformed(evt);
                    ComboVersao.setSelectedItem(tabelaRelatorio.getValueAt(linha, coluna++).toString());
                }else{
                    ButtonLinux.setSelected(true);
                    ButtonLinuxActionPerformed(evt);
                    ComboVersao.setSelectedItem(tabelaRelatorio.getValueAt(linha, coluna++).toString());
                }
                if(tabelaRelatorio.getValueAt(linha, coluna++).toString().equals("AMD")){
                    buttonAmd.setSelected(true);
                }else{
                    buttonIntel.setSelected(true);
                }
                if(tabelaRelatorio.getValueAt(linha, coluna).toString().equals("320 GB")){
                    Check320.setSelected(true);
                }else if(tabelaRelatorio.getValueAt(linha, coluna).toString().equals("500 GB")){
                    Check500.setSelected(true);
                }else{
                    Check1TB.setSelected(true);
                }
                
                listaRAM.setSelectedValue(tabelaRelatorio.getValueAt(linha, ++coluna).toString().replaceAll("[\\[\\]]", ""), true);

                ((DefaultTableModel) tabelaRelatorio.getModel()).removeRow(linha);
            }
        }
    }//GEN-LAST:event_menuAlterarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Exercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Exercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Exercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Exercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Exercicio dialog = new Exercicio(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup ButtonGroupSist;
    private javax.swing.JRadioButton ButtonLinux;
    private javax.swing.JRadioButton ButtonWindows;
    private javax.swing.JCheckBox Check1TB;
    private javax.swing.JCheckBox Check320;
    private javax.swing.JCheckBox Check500;
    private javax.swing.JComboBox<String> ComboCidade;
    private javax.swing.JComboBox<String> ComboVersao;
    private javax.swing.JLabel LabelCidade;
    private javax.swing.JLabel LabelNome;
    private javax.swing.JLabel LabelVersao;
    private javax.swing.JPanel PanelHD;
    private javax.swing.JPanel PanelSist;
    private javax.swing.JTextField TextDigitarNome;
    private javax.swing.JRadioButton buttonAmd;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupHD;
    private javax.swing.JRadioButton buttonIntel;
    private javax.swing.JButton jButtonCadastrar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelRAM;
    private javax.swing.JList<String> listaRAM;
    private javax.swing.JMenuItem menuAlterar;
    private javax.swing.JMenuItem menuCadastrar;
    private javax.swing.JMenuItem menuExcluir;
    private javax.swing.JPopupMenu menuPopUp;
    private javax.swing.JTable tabelaRelatorio;
    // End of variables declaration//GEN-END:variables

    private void inserirRelatorio(String nome, String cidade, String versao, String SO, String processador, String hd, List listRAM) {

        ((DefaultTableModel)tabelaRelatorio.getModel()).addRow(new Object[7]);
        int linha = tabelaRelatorio.getRowCount() - 1;
        int coluna = 0;
        tabelaRelatorio.setValueAt(nome, linha, coluna++);
        tabelaRelatorio.setValueAt(cidade, linha, coluna++);
        tabelaRelatorio.setValueAt(SO, linha, coluna++);
        tabelaRelatorio.setValueAt(versao, linha, coluna++);
        tabelaRelatorio.setValueAt(processador, linha, coluna++);
        tabelaRelatorio.setValueAt(hd, linha, coluna++);
        tabelaRelatorio.setValueAt(listRAM, linha, coluna);
        
                
        
    }

}
